1. Решите линейную систему:

In [59]:
import numpy as np

In [60]:
import warnings

In [61]:
warnings.filterwarnings('ignore')

In [62]:
import scipy.linalg

In [63]:
A=np.array([ [1,2,3], [4,0,6], [7,8,9] ])

In [64]:
B=np.array([12,2,1])

In [65]:
np.linalg.solve(A,B)

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение: x + 2y – z = 1 3x – 4y = 7 8x – 5y + 2z = 12 2x – 5z = 7 11x +4y – 7z = 15

In [66]:
M = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])

In [67]:
V = np.array([1, 7, 12, 7, 15])

In [68]:
R = np.linalg.lstsq(M, V)

In [69]:
R

(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [70]:
print('Псевдорешение: x + 2y – z = 1 3x – 4y = 7 8x – 5y + 2z = 12 2x – 5z = 7 11x +4y – 7z = 15\n =  ', R[0])

Псевдорешение: x + 2y – z = 1 3x – 4y = 7 8x – 5y + 2z = 12 2x – 5z = 7 11x +4y – 7z = 15
 =   [ 1.13919353 -0.90498444 -0.9009803 ]


3. Сколько решений имеет линейная система:

In [71]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [72]:
V = np.array([12, 2, 1])

In [74]:
if abs(round(np.linalg.det(M))) == 0:
    print('Система уравнений вырожденная')
else:
    print('Система уравений имеет решение')

Система уравнений вырожденная


Изменим вектор правой части, чтобы система стала совместной:

In [75]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [76]:
V = np.array([[12, 24, 36]])

In [77]:
C = np.concatenate((M, V.T), axis=1)

In [78]:
C

array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 24],
       [ 7,  8,  9, 36]])

In [79]:
np.linalg.matrix_rank(M, 0.0001), np.linalg.matrix_rank(C, 0.0001)

(2, 2)

4. Вычислите LU-разложение матрицы:

In [80]:
M = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])

In [81]:
P, L, U = scipy.linalg.lu(M)

In [82]:
print('P', P)

P [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [83]:
print('L', L)

L [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]


In [84]:
print('U', U)

U [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [85]:
V = np.array([12, 45, 33])

In [86]:
y = np.linalg.solve(L, V)

In [87]:
x = np.linalg.solve(U, y)

In [88]:
print('Решение:', x)

Решение: [55.51388889 -2.21527778 -2.02777778]


5. Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1
8x – 5y + 2z = 12
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 

In [89]:
def Q(x, y, z):
    return np.linalg.norm(np.array([x, y, z]))

In [90]:
A = np.array([
    [1, 2, -1],
    [8, -5, 2],])

In [91]:
B = np.array([1,12])

In [92]:
print(Q(1, 2, -1))

2.449489742783178


In [93]:
print(Q(8, -5, 2))

9.643650760992955


In [94]:
print(np.linalg.lstsq(A,B))

(array([ 1.38191882, -0.18081181,  0.0202952 ]), array([], dtype=float64), 2, array([9.65316119, 2.41173777]))


6. Найдите одно из псевдорешений вырожденной системы:

In [95]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],])

In [96]:
B = np.array([2,5,11])

In [97]:
print(np.linalg.lstsq(A,B))

(array([ 1.25,  0.5 , -0.25]), array([], dtype=float64), 2, array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))
